import Bookmark from "./JS/bookmark.js";
import Answer from "./JS/show-answer.js";
import OnePage from "./JS/visibilities.js";
import addCard from "./JS/card.js";
import CreateQuestion from "./JS/newQuestion.js";
OnePage();
addCard();
Bookmark();
Answer();
CreateQuestion();
